/**
 * Blueprint Library
 *
 * Pre-defined work blueprints organized by role and category.
 * These are shown to users during onboarding based on their job role.
 */

import { WorkBlueprint, Department, BlueprintCategory } from '@/lib/types/work-blueprints';

/**
 * All available blueprints
 */
export const BLUEPRINT_LIBRARY: WorkBlueprint[] = [
  // ========================================
  // PRODUCT MANAGER BLUEPRINTS
  // ========================================
  {
    id: 'pm-weekly-update',
    name: 'Weekly Stakeholder Update',
    description: 'Send weekly progress update to stakeholders on product initiatives',
    category: 'reporting',
    deliverableType: 'email',
    estimatedTime: '30 minutes',
    frequency: 'weekly',
    typicalDepartments: ['Product'],
  },
  {
    id: 'pm-sprint-planning',
    name: 'Sprint Planning',
    description: 'Prepare for upcoming sprint planning session',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    typicalDepartments: ['Product', 'Engineering'],
  },
  {
    id: 'pm-feature-spec',
    name: 'Feature Specification',
    description: 'Write detailed specification for new product feature',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '4 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Product'],
  },
  {
    id: 'pm-roadmap-review',
    name: 'Quarterly Roadmap Review',
    description: 'Update and review product roadmap for next quarter',
    category: 'planning',
    deliverableType: 'presentation',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Product'],
  },

  // ========================================
  // FINANCE MANAGER BLUEPRINTS
  // ========================================
  {
    id: 'finance-monthly-close',
    name: 'Monthly Financial Close',
    description: 'Complete monthly financial close and reporting',
    category: 'reporting',
    deliverableType: 'spreadsheet',
    estimatedTime: '4 hours',
    frequency: 'monthly',
    typicalDepartments: ['Finance'],
  },
  {
    id: 'finance-budget-review',
    name: 'Budget vs Actuals Review',
    description: 'Review budget performance and identify variances',
    category: 'analysis',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Finance'],
  },
  {
    id: 'finance-vendor-reconciliation',
    name: 'Vendor Payment Reconciliation',
    description: 'Reconcile and process vendor payments',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    typicalDepartments: ['Finance'],
  },
  {
    id: 'finance-board-report',
    name: 'Board Financial Report',
    description: 'Prepare financial metrics and narrative for board meeting',
    category: 'reporting',
    deliverableType: 'presentation',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Finance'],
  },

  // ========================================
  // SALES DIRECTOR BLUEPRINTS
  // ========================================
  {
    id: 'sales-pipeline-review',
    name: 'Weekly Pipeline Review',
    description: 'Review sales pipeline and forecast',
    category: 'reporting',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    typicalDepartments: ['Sales'],
  },
  {
    id: 'sales-qbr-prep',
    name: 'Quarterly Business Review Prep',
    description: 'Prepare for customer QBR meeting',
    category: 'communication',
    deliverableType: 'presentation',
    estimatedTime: '2 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Sales', 'Customer Success'],
  },
  {
    id: 'sales-deal-review',
    name: 'Deal Review & Strategy',
    description: 'Review major deal and plan win strategy',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'ad-hoc',
    typicalDepartments: ['Sales'],
  },

  // ========================================
  // ENGINEERING MANAGER BLUEPRINTS
  // ========================================
  {
    id: 'eng-sprint-retro',
    name: 'Sprint Retrospective',
    description: 'Facilitate team retrospective and document improvements',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '1.5 hours',
    frequency: 'weekly',
    typicalDepartments: ['Engineering'],
  },
  {
    id: 'eng-incident-review',
    name: 'Incident Postmortem',
    description: 'Conduct postmortem after production incident',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Engineering'],
  },
  {
    id: 'eng-hiring-review',
    name: 'Weekly Hiring Pipeline Review',
    description: 'Review engineering hiring pipeline and next steps',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'weekly',
    typicalDepartments: ['Engineering'],
  },

  // ========================================
  // MARKETING MANAGER BLUEPRINTS
  // ========================================
  {
    id: 'marketing-campaign-report',
    name: 'Campaign Performance Report',
    description: 'Analyze and report on marketing campaign results',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Marketing'],
  },
  {
    id: 'marketing-content-plan',
    name: 'Monthly Content Calendar',
    description: 'Plan content calendar for next month',
    category: 'planning',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Marketing'],
  },

  // ========================================
  // OPERATIONS MANAGER BLUEPRINTS
  // ========================================
  {
    id: 'ops-process-review',
    name: 'Process Efficiency Review',
    description: 'Review and optimize operational process',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-vendor-review',
    name: 'Vendor Performance Review',
    description: 'Review vendor performance and contract renewal',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '1.5 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Operations'],
  },

  // ========================================
  // OPERATIONS BLUEPRINTS
  // ========================================
  {
    id: 'ops-payments-processing',
    name: 'Payments Processing',
    description: 'Handle incoming and outgoing payment instructions',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-corporate-onboarding',
    name: 'Corporate Client Onboarding',
    description: 'Onboard new corporate clients with full KYC',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '4 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-retail-onboarding',
    name: 'Retail Onboarding',
    description: 'Onboard retail customers efficiently',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-kyc-updates',
    name: 'KYC Updates',
    description: 'Periodic review and update of customer documentation',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'quarterly',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-loan-disbursement',
    name: 'Loan Disbursement',
    description: 'Process approved loans for disbursement',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '1.5 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-card-activation',
    name: 'Card Activation',
    description: 'Activate new cards for customers',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-atm-operations',
    name: 'ATM Operations',
    description: 'Monitor and manage ATM network',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-reconciliations',
    name: 'Reconciliations',
    description: 'Daily account and transaction reconciliation',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '3 hours',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-customer-data-updates',
    name: 'Customer Data Updates',
    description: 'Process customer information changes',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-digital-banking-support',
    name: 'Digital Banking Support',
    description: 'Support digital channel issues',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-batch-processing',
    name: 'Batch Processing',
    description: 'Process bulk transactions overnight',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
  },
  {
    id: 'ops-exception-handling',
    name: 'Exception Handling',
    description: 'Manage failed or stuck transactions',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
  },

  // ========================================
  // ADDITIONAL FINANCE BLUEPRINTS
  // ========================================
  {
    id: 'finance-expense-approvals',
    name: 'Expense Approvals',
    description: 'Review and approve expense claims',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    typicalDepartments: ['Finance'],
  },
  {
    id: 'finance-audit-prep',
    name: 'Audit Preparation',
    description: 'Prepare documentation for audits',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '4 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Finance'],
  },
  {
    id: 'finance-cost-allocation',
    name: 'Cost Allocation',
    description: 'Allocate costs across departments',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Finance'],
  },
  {
    id: 'finance-tax-compliance',
    name: 'Tax Compliance',
    description: 'Ensure tax filings are accurate and timely',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Finance'],
  },

  // ========================================
  // HR BLUEPRINTS
  // ========================================
  {
    id: 'hr-employee-onboarding',
    name: 'Employee Onboarding',
    description: 'Onboard new hires with paperwork and training',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Human Resources'],
  },
  {
    id: 'hr-payroll-processing',
    name: 'Payroll Processing',
    description: 'Process monthly payroll',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '4 hours',
    frequency: 'monthly',
    typicalDepartments: ['Human Resources'],
  },
  {
    id: 'hr-performance-reviews',
    name: 'Performance Reviews',
    description: 'Conduct annual performance evaluations',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Human Resources'],
  },
  {
    id: 'hr-leave-management',
    name: 'Leave Management',
    description: 'Approve and track employee leave',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    typicalDepartments: ['Human Resources'],
  },
  {
    id: 'hr-offboarding',
    name: 'Offboarding',
    description: 'Process employee exits',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Human Resources'],
  },
  {
    id: 'hr-training-coordination',
    name: 'Training Coordination',
    description: 'Schedule and track employee training',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Human Resources'],
  },
  {
    id: 'hr-benefits-admin',
    name: 'Benefits Administration',
    description: 'Manage employee benefits programs',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Human Resources'],
  },
  {
    id: 'hr-workforce-planning',
    name: 'Workforce Planning',
    description: 'Plan staffing needs and capacity',
    category: 'planning',
    deliverableType: 'spreadsheet',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Human Resources'],
  },

  // ========================================
  // IT BLUEPRINTS
  // ========================================
  {
    id: 'it-access-provisioning',
    name: 'Access Provisioning',
    description: 'Grant and revoke system access',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Engineering'],
  },
  {
    id: 'it-change-management',
    name: 'Change Management',
    description: 'Process system change requests',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    typicalDepartments: ['Engineering'],
  },
  {
    id: 'it-system-maintenance',
    name: 'System Maintenance',
    description: 'Perform regular system updates',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'monthly',
    typicalDepartments: ['Engineering'],
  },
  {
    id: 'it-security-monitoring',
    name: 'Security Monitoring',
    description: 'Monitor for security threats',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
    typicalDepartments: ['Engineering'],
  },
  {
    id: 'it-disaster-recovery',
    name: 'Disaster Recovery',
    description: 'Test and maintain DR procedures',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '4 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Engineering'],
  },
  {
    id: 'it-vendor-onboarding',
    name: 'Vendor Onboarding',
    description: 'Onboard new technology vendors',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Engineering'],
  },
  {
    id: 'it-license-management',
    name: 'License Management',
    description: 'Track and renew software licenses',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'monthly',
    typicalDepartments: ['Engineering'],
  },

  // ========================================
  // ADDITIONAL SALES BLUEPRINTS
  // ========================================
  {
    id: 'sales-lead-qualification',
    name: 'Lead Qualification',
    description: 'Qualify incoming leads',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Sales'],
  },
  {
    id: 'sales-proposal-creation',
    name: 'Proposal Creation',
    description: 'Create client proposals',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    typicalDepartments: ['Sales'],
  },
  {
    id: 'sales-contract-negotiation',
    name: 'Contract Negotiation',
    description: 'Negotiate and close deals',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Sales'],
  },
  {
    id: 'sales-client-renewals',
    name: 'Client Renewals',
    description: 'Manage contract renewals',
    category: 'operations',
    deliverableType: 'email',
    estimatedTime: '1 hour',
    frequency: 'monthly',
    typicalDepartments: ['Sales', 'Customer Success'],
  },
  {
    id: 'sales-quote-generation',
    name: 'Quote Generation',
    description: 'Create and send price quotes',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Sales'],
  },
  {
    id: 'sales-territory-management',
    name: 'Territory Management',
    description: 'Manage sales territories and assignments',
    category: 'planning',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Sales'],
  },
  {
    id: 'sales-commission-tracking',
    name: 'Commission Tracking',
    description: 'Calculate and track sales commissions',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Sales'],
  },

  // ========================================
  // CUSTOMER SERVICE BLUEPRINTS
  // ========================================
  {
    id: 'cs-complaint-handling',
    name: 'Complaint Handling',
    description: 'Resolve customer complaints',
    category: 'operations',
    deliverableType: 'email',
    estimatedTime: '1 hour',
    frequency: 'daily',
    typicalDepartments: ['Customer Success'],
  },
  {
    id: 'cs-query-resolution',
    name: 'Query Resolution',
    description: 'Answer customer queries',
    category: 'operations',
    deliverableType: 'email',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Customer Success'],
  },
  {
    id: 'cs-account-inquiries',
    name: 'Account Inquiries',
    description: 'Handle account-related questions',
    category: 'operations',
    deliverableType: 'email',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Customer Success'],
  },
  {
    id: 'cs-escalation-management',
    name: 'Escalation Management',
    description: 'Manage escalated issues',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '1.5 hours',
    frequency: 'weekly',
    typicalDepartments: ['Customer Success'],
  },
  {
    id: 'cs-feedback-collection',
    name: 'Feedback Collection',
    description: 'Gather customer feedback',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '1 hour',
    frequency: 'monthly',
    typicalDepartments: ['Customer Success'],
  },
  {
    id: 'cs-sla-monitoring',
    name: 'SLA Monitoring',
    description: 'Track service level agreement compliance',
    category: 'reporting',
    deliverableType: 'report',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    typicalDepartments: ['Customer Success'],
  },
  {
    id: 'cs-knowledge-base-updates',
    name: 'Knowledge Base Updates',
    description: 'Maintain customer support documentation',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Customer Success'],
  },
  {
    id: 'cs-channel-management',
    name: 'Channel Management',
    description: 'Manage multi-channel support queues',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '1 hour',
    frequency: 'daily',
    typicalDepartments: ['Customer Success'],
  },

  // ========================================
  // ADDITIONAL MARKETING BLUEPRINTS
  // ========================================
  {
    id: 'marketing-social-media',
    name: 'Social Media Management',
    description: 'Manage social media presence and engagement',
    category: 'communication',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'daily',
    typicalDepartments: ['Marketing'],
  },
  {
    id: 'marketing-brand-guidelines',
    name: 'Brand Guidelines',
    description: 'Maintain and enforce brand standards',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Marketing'],
  },
  {
    id: 'marketing-event-management',
    name: 'Event Management',
    description: 'Plan and execute marketing events',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '5 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Marketing'],
  },
  {
    id: 'marketing-analytics',
    name: 'Marketing Analytics',
    description: 'Track and report on campaign performance',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Marketing'],
  },
  {
    id: 'marketing-lead-nurturing',
    name: 'Lead Nurturing',
    description: 'Nurture leads through email campaigns',
    category: 'communication',
    deliverableType: 'email',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    typicalDepartments: ['Marketing'],
  },
  {
    id: 'marketing-partner-marketing',
    name: 'Partner Marketing',
    description: 'Coordinate co-marketing with partners',
    category: 'coordination',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'monthly',
    typicalDepartments: ['Marketing'],
  },
  {
    id: 'marketing-budget-tracking',
    name: 'Budget Tracking',
    description: 'Track marketing spend and ROI',
    category: 'reporting',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'monthly',
    typicalDepartments: ['Marketing'],
  },

  // ========================================
  // LEGAL BLUEPRINTS
  // ========================================
  {
    id: 'legal-contract-review',
    name: 'Contract Review',
    description: 'Review and approve legal contracts',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'weekly',
  },
  {
    id: 'legal-regulatory-filings',
    name: 'Regulatory Filings',
    description: 'Prepare and submit regulatory documents',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
  },
  {
    id: 'legal-litigation-management',
    name: 'Litigation Management',
    description: 'Manage legal disputes and cases',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '4 hours',
    frequency: 'ad-hoc',
  },
  {
    id: 'legal-policy-updates',
    name: 'Policy Updates',
    description: 'Update internal policies and procedures',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'quarterly',
  },
  {
    id: 'legal-advisory',
    name: 'Legal Advisory',
    description: 'Provide legal guidance to business units',
    category: 'operations',
    deliverableType: 'email',
    estimatedTime: '1 hour',
    frequency: 'weekly',
  },
  {
    id: 'legal-ip-management',
    name: 'IP Management',
    description: 'Track patents and trademarks',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '1.5 hours',
    frequency: 'quarterly',
  },
  {
    id: 'legal-nda-processing',
    name: 'NDA Processing',
    description: 'Process non-disclosure agreements',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'weekly',
  },
  {
    id: 'legal-research',
    name: 'Legal Research',
    description: 'Research legal precedents and regulations',
    category: 'analysis',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
  },

  // ========================================
  // COMPLIANCE BLUEPRINTS
  // ========================================
  {
    id: 'compliance-regulatory-monitoring',
    name: 'Regulatory Monitoring',
    description: 'Monitor regulatory changes and updates',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'weekly',
  },
  {
    id: 'compliance-testing',
    name: 'Compliance Testing',
    description: 'Test adherence to regulatory requirements',
    category: 'review',
    deliverableType: 'report',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
  },
  {
    id: 'compliance-aml-screening',
    name: 'AML Screening',
    description: 'Screen transactions for money laundering',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
  },
  {
    id: 'compliance-sanctions-checks',
    name: 'Sanctions Checks',
    description: 'Verify against sanctions lists',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '1 hour',
    frequency: 'daily',
  },
  {
    id: 'compliance-reporting',
    name: 'Compliance Reporting',
    description: 'Generate compliance reports for regulators',
    category: 'reporting',
    deliverableType: 'report',
    estimatedTime: '3 hours',
    frequency: 'monthly',
  },
  {
    id: 'compliance-policy-enforcement',
    name: 'Policy Enforcement',
    description: 'Ensure policies are followed across teams',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
  },
  {
    id: 'compliance-training-tracking',
    name: 'Training Tracking',
    description: 'Track compliance training completion',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'monthly',
  },
  {
    id: 'compliance-incident-reporting',
    name: 'Incident Reporting',
    description: 'Report compliance incidents',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
  },
  {
    id: 'compliance-vendor-due-diligence',
    name: 'Vendor Due Diligence',
    description: 'Assess third-party compliance',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
  },

  // ========================================
  // RISK BLUEPRINTS
  // ========================================
  {
    id: 'risk-assessment',
    name: 'Risk Assessment',
    description: 'Evaluate and document business risks',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
  },
  {
    id: 'risk-credit-analysis',
    name: 'Credit Analysis',
    description: 'Analyze creditworthiness of clients',
    category: 'analysis',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
  },
  {
    id: 'risk-fraud-detection',
    name: 'Fraud Detection',
    description: 'Identify and investigate fraud patterns',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
  },
  {
    id: 'risk-reporting',
    name: 'Risk Reporting',
    description: 'Prepare risk reports for management',
    category: 'reporting',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
  },
  {
    id: 'risk-stress-testing',
    name: 'Stress Testing',
    description: 'Conduct scenario-based stress tests',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '4 hours',
    frequency: 'quarterly',
  },
  {
    id: 'risk-incident-response',
    name: 'Incident Response',
    description: 'Respond to risk events and incidents',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'ad-hoc',
  },
  {
    id: 'risk-control-testing',
    name: 'Control Testing',
    description: 'Test effectiveness of risk controls',
    category: 'review',
    deliverableType: 'report',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
  },
  {
    id: 'risk-appetite-monitoring',
    name: 'Appetite Monitoring',
    description: 'Monitor against risk appetite limits',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '1.5 hours',
    frequency: 'monthly',
  },

  // ========================================
  // ADDITIONAL PRODUCT BLUEPRINTS
  // ========================================
  {
    id: 'product-requirements-gathering',
    name: 'Requirements Gathering',
    description: 'Collect and document product requirements',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Product'],
  },
  {
    id: 'product-user-research',
    name: 'User Research',
    description: 'Conduct user interviews and surveys',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '4 hours',
    frequency: 'monthly',
    typicalDepartments: ['Product'],
  },
  {
    id: 'product-feature-testing',
    name: 'Feature Testing',
    description: 'Test new features before release',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    typicalDepartments: ['Product'],
  },
  {
    id: 'product-launch',
    name: 'Product Launch',
    description: 'Coordinate product launches and rollouts',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '5 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Product'],
  },
  {
    id: 'product-backlog-grooming',
    name: 'Backlog Grooming',
    description: 'Prioritize and refine product backlog',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '1.5 hours',
    frequency: 'weekly',
    typicalDepartments: ['Product'],
  },
  {
    id: 'product-competitor-analysis',
    name: 'Competitor Analysis',
    description: 'Track and analyze competitor products',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Product'],
  },
  {
    id: 'product-beta-management',
    name: 'Beta Management',
    description: 'Manage beta testing programs',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Product'],
  },
  {
    id: 'product-feedback-synthesis',
    name: 'Feedback Synthesis',
    description: 'Analyze and prioritize user feedback',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Product'],
  },

  // ========================================
  // ACCOUNTING / FINANCE SKILLS
  // ========================================
  {
    id: 'invoice-extract-classify',
    name: 'Invoice Extraction & Classification',
    description: 'Upload invoice files (PDF or images) and get a structured spreadsheet with all invoice data extracted and categorized automatically.',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 minutes',
    frequency: 'ad-hoc',
    typicalDepartments: ['Finance', 'Operations', 'Other'],
  },

  // ========================================
  // GENERAL / CROSS-FUNCTIONAL BLUEPRINTS
  // ========================================
  {
    id: 'general-team-meeting',
    name: 'Team Meeting Prep',
    description: 'Prepare agenda and materials for team meeting',
    category: 'communication',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'weekly',
  },
  {
    id: 'general-1on1-prep',
    name: '1-on-1 Meeting Prep',
    description: 'Prepare for 1-on-1 with direct report or manager',
    category: 'communication',
    deliverableType: 'document',
    estimatedTime: '15 minutes',
    frequency: 'weekly',
  },
  {
    id: 'general-project-status',
    name: 'Project Status Update',
    description: 'Send project status update to stakeholders',
    category: 'reporting',
    deliverableType: 'email',
    estimatedTime: '30 minutes',
    frequency: 'weekly',
  },
];

/**
 * Get blueprints relevant to a department
 */
export function getBlueprintsForDepartment(department: Department): WorkBlueprint[] {
  return BLUEPRINT_LIBRARY.filter(bp =>
    bp.typicalDepartments && bp.typicalDepartments.includes(department)
  );
}

/**
 * Get blueprints by category
 */
export function getBlueprintsByCategory(category: BlueprintCategory): WorkBlueprint[] {
  return BLUEPRINT_LIBRARY.filter(bp => bp.category === category);
}

/**
 * Get blueprint by ID
 */
export function getBlueprintById(id: string): WorkBlueprint | undefined {
  return BLUEPRINT_LIBRARY.find(bp => bp.id === id);
}

/**
 * Get all blueprints (for browsing)
 */
export function getAllBlueprints(): WorkBlueprint[] {
  return BLUEPRINT_LIBRARY;
}
