/**
 * Blueprint Library
 *
 * Pre-defined work blueprints organized by role and category.
 * These are shown to users during onboarding based on their job role.
 */

import { WorkBlueprint, Department, BlueprintCategory } from '@/lib/types/work-blueprints';

/**
 * All available blueprints
 */
export const BLUEPRINT_LIBRARY: WorkBlueprint[] = [
  // ========================================
  // PRODUCT MANAGER BLUEPRINTS
  // ========================================
  {
    id: 'pm-weekly-update',
    name: 'Weekly Stakeholder Update',
    description: 'Send weekly progress update to stakeholders on product initiatives',
    category: 'reporting',
    deliverableType: 'email',
    estimatedTime: '30 minutes',
    frequency: 'weekly',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Review completed work from past week' },
      { number: 2, action: 'Identify key wins and blockers' },
      { number: 3, action: 'Draft update email with metrics' },
      { number: 4, action: 'Send to stakeholders' },
    ],
  },
  {
    id: 'pm-sprint-planning',
    name: 'Sprint Planning',
    description: 'Prepare for upcoming sprint planning session',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    typicalDepartments: ['Product', 'Engineering'],
    defaultSteps: [
      { number: 1, action: 'Review product backlog and priorities' },
      { number: 2, action: 'Identify stories ready for development' },
      { number: 3, action: 'Write acceptance criteria for top items' },
      { number: 4, action: 'Coordinate with engineering on estimates' },
      { number: 5, action: 'Create sprint goal and plan' },
    ],
  },
  {
    id: 'pm-feature-spec',
    name: 'Feature Specification',
    description: 'Write detailed specification for new product feature',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '4 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Define problem statement and user needs' },
      { number: 2, action: 'Outline proposed solution and alternatives' },
      { number: 3, action: 'Write detailed user flows and edge cases' },
      { number: 4, action: 'Define success metrics and acceptance criteria' },
      { number: 5, action: 'Review with design and engineering' },
    ],
  },
  {
    id: 'pm-roadmap-review',
    name: 'Quarterly Roadmap Review',
    description: 'Update and review product roadmap for next quarter',
    category: 'planning',
    deliverableType: 'presentation',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Review Q goals and priorities' },
      { number: 2, action: 'Assess progress on current initiatives' },
      { number: 3, action: 'Update roadmap with new priorities' },
      { number: 4, action: 'Create presentation for leadership' },
      { number: 5, action: 'Schedule review meeting' },
    ],
  },

  // ========================================
  // FINANCE MANAGER BLUEPRINTS
  // ========================================
  {
    id: 'finance-monthly-close',
    name: 'Monthly Financial Close',
    description: 'Complete monthly financial close and reporting',
    category: 'reporting',
    deliverableType: 'spreadsheet',
    estimatedTime: '4 hours',
    frequency: 'monthly',
    typicalDepartments: ['Finance'],
    defaultSteps: [
      { number: 1, action: 'Reconcile all accounts' },
      { number: 2, action: 'Review and categorize transactions' },
      { number: 3, action: 'Generate financial statements' },
      { number: 4, action: 'Prepare variance analysis' },
      { number: 5, action: 'Review with CFO and distribute reports' },
    ],
  },
  {
    id: 'finance-budget-review',
    name: 'Budget vs Actuals Review',
    description: 'Review budget performance and identify variances',
    category: 'analysis',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Finance'],
    defaultSteps: [
      { number: 1, action: 'Pull actual spend data by department' },
      { number: 2, action: 'Compare to budgeted amounts' },
      { number: 3, action: 'Identify significant variances (>10%)' },
      { number: 4, action: 'Investigate root causes with department heads' },
      { number: 5, action: 'Update forecast if needed' },
    ],
  },
  {
    id: 'finance-vendor-reconciliation',
    name: 'Vendor Payment Reconciliation',
    description: 'Reconcile and process vendor payments',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    typicalDepartments: ['Finance'],
    defaultSteps: [
      { number: 1, action: 'Review outstanding vendor invoices' },
      { number: 2, action: 'Verify invoice accuracy against POs' },
      { number: 3, action: 'Approve payments in system' },
      { number: 4, action: 'Update accounts payable aging report' },
    ],
  },
  {
    id: 'finance-board-report',
    name: 'Board Financial Report',
    description: 'Prepare financial metrics and narrative for board meeting',
    category: 'reporting',
    deliverableType: 'presentation',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Finance'],
    defaultSteps: [
      { number: 1, action: 'Gather key financial metrics (revenue, EBITDA, cash)' },
      { number: 2, action: 'Create visualizations and trend charts' },
      { number: 3, action: 'Write executive summary of performance' },
      { number: 4, action: 'Prepare deck with CFO commentary' },
      { number: 5, action: 'Review with CEO before board meeting' },
    ],
  },

  // ========================================
  // SALES DIRECTOR BLUEPRINTS
  // ========================================
  {
    id: 'sales-pipeline-review',
    name: 'Weekly Pipeline Review',
    description: 'Review sales pipeline and forecast',
    category: 'reporting',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    typicalDepartments: ['Sales'],
    defaultSteps: [
      { number: 1, action: 'Pull latest pipeline data from CRM' },
      { number: 2, action: 'Review deal progression and stalled deals' },
      { number: 3, action: 'Update win probability and close dates' },
      { number: 4, action: 'Prepare forecast for leadership' },
    ],
  },
  {
    id: 'sales-qbr-prep',
    name: 'Quarterly Business Review Prep',
    description: 'Prepare for customer QBR meeting',
    category: 'communication',
    deliverableType: 'presentation',
    estimatedTime: '2 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Sales', 'Customer Success'],
    defaultSteps: [
      { number: 1, action: 'Review account health and usage metrics' },
      { number: 2, action: 'Identify wins and areas for improvement' },
      { number: 3, action: 'Prepare recommendations and upsell opportunities' },
      { number: 4, action: 'Create QBR deck with exec summary' },
      { number: 5, action: 'Send pre-read to customer' },
    ],
  },
  {
    id: 'sales-deal-review',
    name: 'Deal Review & Strategy',
    description: 'Review major deal and plan win strategy',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'ad-hoc',
    typicalDepartments: ['Sales'],
    defaultSteps: [
      { number: 1, action: 'Document deal details and stakeholders' },
      { number: 2, action: 'Identify decision criteria and buying process' },
      { number: 3, action: 'Map out competition and differentiators' },
      { number: 4, action: 'Create win strategy and next steps' },
    ],
  },

  // ========================================
  // ENGINEERING MANAGER BLUEPRINTS
  // ========================================
  {
    id: 'eng-sprint-retro',
    name: 'Sprint Retrospective',
    description: 'Facilitate team retrospective and document improvements',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '1.5 hours',
    frequency: 'weekly',
    typicalDepartments: ['Engineering'],
    defaultSteps: [
      { number: 1, action: 'Review sprint goals and outcomes' },
      { number: 2, action: 'Gather team feedback (what went well, what to improve)' },
      { number: 3, action: 'Identify action items and owners' },
      { number: 4, action: 'Document and share retro notes' },
    ],
  },
  {
    id: 'eng-incident-review',
    name: 'Incident Postmortem',
    description: 'Conduct postmortem after production incident',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Engineering'],
    defaultSteps: [
      { number: 1, action: 'Document incident timeline and impact' },
      { number: 2, action: 'Identify root cause(s)' },
      { number: 3, action: 'List action items to prevent recurrence' },
      { number: 4, action: 'Share postmortem with team and stakeholders' },
    ],
  },
  {
    id: 'eng-hiring-review',
    name: 'Weekly Hiring Pipeline Review',
    description: 'Review engineering hiring pipeline and next steps',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'weekly',
    typicalDepartments: ['Engineering'],
    defaultSteps: [
      { number: 1, action: 'Review active candidates and interview stages' },
      { number: 2, action: 'Follow up on pending feedback' },
      { number: 3, action: 'Schedule next round interviews' },
      { number: 4, action: 'Update hiring tracker' },
    ],
  },

  // ========================================
  // MARKETING MANAGER BLUEPRINTS
  // ========================================
  {
    id: 'marketing-campaign-report',
    name: 'Campaign Performance Report',
    description: 'Analyze and report on marketing campaign results',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Marketing'],
    defaultSteps: [
      { number: 1, action: 'Pull campaign metrics (impressions, clicks, conversions)' },
      { number: 2, action: 'Calculate ROI and cost per acquisition' },
      { number: 3, action: 'Identify top performing channels and content' },
      { number: 4, action: 'Create report with insights and recommendations' },
      { number: 5, action: 'Present to leadership' },
    ],
  },
  {
    id: 'marketing-content-plan',
    name: 'Monthly Content Calendar',
    description: 'Plan content calendar for next month',
    category: 'planning',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Marketing'],
    defaultSteps: [
      { number: 1, action: 'Review content themes and priorities' },
      { number: 2, action: 'Brainstorm topics and assign to writers' },
      { number: 3, action: 'Schedule publication dates' },
      { number: 4, action: 'Coordinate with design and social teams' },
    ],
  },

  // ========================================
  // OPERATIONS MANAGER BLUEPRINTS
  // ========================================
  {
    id: 'ops-process-review',
    name: 'Process Efficiency Review',
    description: 'Review and optimize operational process',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Map current process flow' },
      { number: 2, action: 'Identify bottlenecks and inefficiencies' },
      { number: 3, action: 'Design optimized process' },
      { number: 4, action: 'Document changes and train team' },
    ],
  },
  {
    id: 'ops-vendor-review',
    name: 'Vendor Performance Review',
    description: 'Review vendor performance and contract renewal',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '1.5 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Review SLA compliance and service quality' },
      { number: 2, action: 'Analyze cost vs value' },
      { number: 3, action: 'Document issues and improvement requests' },
      { number: 4, action: 'Decide on renewal, renegotiation, or replacement' },
    ],
  },

  // ========================================
  // OPERATIONS BLUEPRINTS
  // ========================================
  {
    id: 'ops-payments-processing',
    name: 'Payments Processing',
    description: 'Handle incoming and outgoing payment instructions',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Review payment queue for new instructions' },
      { number: 2, action: 'Verify payment details and authorization' },
      { number: 3, action: 'Process approved payments' },
      { number: 4, action: 'Update payment tracking system' },
      { number: 5, action: 'Send confirmation notifications' },
    ],
  },
  {
    id: 'ops-corporate-onboarding',
    name: 'Corporate Client Onboarding',
    description: 'Onboard new corporate clients with full KYC',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '4 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Collect company documentation and KYC forms' },
      { number: 2, action: 'Verify business registration and ownership' },
      { number: 3, action: 'Complete due diligence checks' },
      { number: 4, action: 'Set up account and access credentials' },
      { number: 5, action: 'Send welcome package and onboarding materials' },
    ],
  },
  {
    id: 'ops-retail-onboarding',
    name: 'Retail Onboarding',
    description: 'Onboard retail customers efficiently',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Review customer application and documentation' },
      { number: 2, action: 'Verify identity and perform KYC checks' },
      { number: 3, action: 'Create customer account in system' },
      { number: 4, action: 'Issue account details and credentials' },
      { number: 5, action: 'Schedule onboarding call or send welcome email' },
    ],
  },
  {
    id: 'ops-kyc-updates',
    name: 'KYC Updates',
    description: 'Periodic review and update of customer documentation',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'quarterly',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Identify customers due for KYC refresh' },
      { number: 2, action: 'Request updated documentation from customers' },
      { number: 3, action: 'Review and verify new documents' },
      { number: 4, action: 'Update customer records in system' },
      { number: 5, action: 'Document review completion' },
    ],
  },
  {
    id: 'ops-loan-disbursement',
    name: 'Loan Disbursement',
    description: 'Process approved loans for disbursement',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '1.5 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Verify loan approval and documentation' },
      { number: 2, action: 'Confirm disbursement account details' },
      { number: 3, action: 'Process disbursement transaction' },
      { number: 4, action: 'Update loan management system' },
      { number: 5, action: 'Send disbursement confirmation to customer' },
    ],
  },
  {
    id: 'ops-card-activation',
    name: 'Card Activation',
    description: 'Activate new cards for customers',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Verify customer identity and card details' },
      { number: 2, action: 'Activate card in system' },
      { number: 3, action: 'Set initial PIN or security settings' },
      { number: 4, action: 'Send activation confirmation' },
    ],
  },
  {
    id: 'ops-atm-operations',
    name: 'ATM Operations',
    description: 'Monitor and manage ATM network',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Check ATM status dashboard for alerts' },
      { number: 2, action: 'Review cash levels and usage patterns' },
      { number: 3, action: 'Coordinate cash replenishment for low-balance ATMs' },
      { number: 4, action: 'Address any technical issues or outages' },
      { number: 5, action: 'Update operations log' },
    ],
  },
  {
    id: 'ops-reconciliations',
    name: 'Reconciliations',
    description: 'Daily account and transaction reconciliation',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '3 hours',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Export transaction data from all systems' },
      { number: 2, action: 'Match transactions across systems' },
      { number: 3, action: 'Identify and investigate discrepancies' },
      { number: 4, action: 'Make correcting entries as needed' },
      { number: 5, action: 'Document reconciliation results' },
    ],
  },
  {
    id: 'ops-customer-data-updates',
    name: 'Customer Data Updates',
    description: 'Process customer information changes',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Review customer update requests' },
      { number: 2, action: 'Verify supporting documentation' },
      { number: 3, action: 'Update customer records in system' },
      { number: 4, action: 'Send confirmation to customer' },
    ],
  },
  {
    id: 'ops-digital-banking-support',
    name: 'Digital Banking Support',
    description: 'Support digital channel issues',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Review digital banking incident queue' },
      { number: 2, action: 'Troubleshoot technical issues' },
      { number: 3, action: 'Escalate complex issues to IT' },
      { number: 4, action: 'Update customers on resolution status' },
      { number: 5, action: 'Document issues and resolutions' },
    ],
  },
  {
    id: 'ops-batch-processing',
    name: 'Batch Processing',
    description: 'Process bulk transactions overnight',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Prepare batch files for processing' },
      { number: 2, action: 'Initiate batch job execution' },
      { number: 3, action: 'Monitor batch processing status' },
      { number: 4, action: 'Review processing results and exceptions' },
      { number: 5, action: 'Generate batch completion report' },
    ],
  },
  {
    id: 'ops-exception-handling',
    name: 'Exception Handling',
    description: 'Manage failed or stuck transactions',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
    typicalDepartments: ['Operations'],
    defaultSteps: [
      { number: 1, action: 'Review exception queue for failed transactions' },
      { number: 2, action: 'Investigate root cause of each exception' },
      { number: 3, action: 'Resolve or reprocess transactions' },
      { number: 4, action: 'Escalate unresolved exceptions' },
      { number: 5, action: 'Document exception resolutions' },
    ],
  },

  // ========================================
  // ADDITIONAL FINANCE BLUEPRINTS
  // ========================================
  {
    id: 'finance-expense-approvals',
    name: 'Expense Approvals',
    description: 'Review and approve expense claims',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    typicalDepartments: ['Finance'],
    defaultSteps: [
      { number: 1, action: 'Review pending expense claims' },
      { number: 2, action: 'Verify receipts and policy compliance' },
      { number: 3, action: 'Approve or reject claims with comments' },
      { number: 4, action: 'Process approved claims for payment' },
    ],
  },
  {
    id: 'finance-audit-prep',
    name: 'Audit Preparation',
    description: 'Prepare documentation for audits',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '4 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Finance'],
    defaultSteps: [
      { number: 1, action: 'Review audit requirements and scope' },
      { number: 2, action: 'Gather required financial documents' },
      { number: 3, action: 'Prepare supporting schedules and reconciliations' },
      { number: 4, action: 'Organize documents for auditor access' },
      { number: 5, action: 'Coordinate with auditors on timeline' },
    ],
  },
  {
    id: 'finance-cost-allocation',
    name: 'Cost Allocation',
    description: 'Allocate costs across departments',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Finance'],
    defaultSteps: [
      { number: 1, action: 'Review shared costs to be allocated' },
      { number: 2, action: 'Calculate allocation percentages by department' },
      { number: 3, action: 'Update cost allocation spreadsheet' },
      { number: 4, action: 'Post allocation entries to general ledger' },
      { number: 5, action: 'Share allocation report with department heads' },
    ],
  },
  {
    id: 'finance-tax-compliance',
    name: 'Tax Compliance',
    description: 'Ensure tax filings are accurate and timely',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Finance'],
    defaultSteps: [
      { number: 1, action: 'Gather financial data for tax period' },
      { number: 2, action: 'Calculate tax liability' },
      { number: 3, action: 'Prepare tax returns and schedules' },
      { number: 4, action: 'Review with tax advisor' },
      { number: 5, action: 'Submit filings and make payments' },
    ],
  },

  // ========================================
  // HR BLUEPRINTS
  // ========================================
  {
    id: 'hr-employee-onboarding',
    name: 'Employee Onboarding',
    description: 'Onboard new hires with paperwork and training',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Human Resources'],
    defaultSteps: [
      { number: 1, action: 'Send offer letter and collect signed documents' },
      { number: 2, action: 'Set up payroll and benefits enrollment' },
      { number: 3, action: 'Coordinate with IT for equipment and access' },
      { number: 4, action: 'Schedule orientation and training sessions' },
      { number: 5, action: 'Assign onboarding buddy and check-in schedule' },
    ],
  },
  {
    id: 'hr-payroll-processing',
    name: 'Payroll Processing',
    description: 'Process monthly payroll',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '4 hours',
    frequency: 'monthly',
    typicalDepartments: ['Human Resources'],
    defaultSteps: [
      { number: 1, action: 'Collect timesheets and attendance data' },
      { number: 2, action: 'Calculate salaries, bonuses, and deductions' },
      { number: 3, action: 'Review payroll for accuracy' },
      { number: 4, action: 'Submit payroll for bank transfer' },
      { number: 5, action: 'Distribute payslips to employees' },
    ],
  },
  {
    id: 'hr-performance-reviews',
    name: 'Performance Reviews',
    description: 'Conduct annual performance evaluations',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Human Resources'],
    defaultSteps: [
      { number: 1, action: 'Send review forms to managers and employees' },
      { number: 2, action: 'Collect self-assessments and manager feedback' },
      { number: 3, action: 'Schedule review meetings' },
      { number: 4, action: 'Document review outcomes and development plans' },
      { number: 5, action: 'Process any compensation changes' },
    ],
  },
  {
    id: 'hr-leave-management',
    name: 'Leave Management',
    description: 'Approve and track employee leave',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    typicalDepartments: ['Human Resources'],
    defaultSteps: [
      { number: 1, action: 'Review pending leave requests' },
      { number: 2, action: 'Check leave balances and eligibility' },
      { number: 3, action: 'Approve or request adjustments' },
      { number: 4, action: 'Update leave tracking system' },
      { number: 5, action: 'Notify employees of approval status' },
    ],
  },
  {
    id: 'hr-offboarding',
    name: 'Offboarding',
    description: 'Process employee exits',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Human Resources'],
    defaultSteps: [
      { number: 1, action: 'Conduct exit interview' },
      { number: 2, action: 'Coordinate equipment and access revocation with IT' },
      { number: 3, action: 'Process final payroll and benefits' },
      { number: 4, action: 'Collect company property' },
      { number: 5, action: 'Update HR systems and file records' },
    ],
  },
  {
    id: 'hr-training-coordination',
    name: 'Training Coordination',
    description: 'Schedule and track employee training',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Human Resources'],
    defaultSteps: [
      { number: 1, action: 'Identify training needs and requirements' },
      { number: 2, action: 'Schedule training sessions and book resources' },
      { number: 3, action: 'Communicate training details to employees' },
      { number: 4, action: 'Track attendance and completion' },
      { number: 5, action: 'Collect feedback and update training records' },
    ],
  },
  {
    id: 'hr-benefits-admin',
    name: 'Benefits Administration',
    description: 'Manage employee benefits programs',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Human Resources'],
    defaultSteps: [
      { number: 1, action: 'Process new benefits enrollments' },
      { number: 2, action: 'Handle benefits changes and updates' },
      { number: 3, action: 'Coordinate with benefits providers' },
      { number: 4, action: 'Respond to employee benefits questions' },
      { number: 5, action: 'Update benefits documentation' },
    ],
  },
  {
    id: 'hr-workforce-planning',
    name: 'Workforce Planning',
    description: 'Plan staffing needs and capacity',
    category: 'planning',
    deliverableType: 'spreadsheet',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Human Resources'],
    defaultSteps: [
      { number: 1, action: 'Review current headcount and open positions' },
      { number: 2, action: 'Forecast hiring needs by department' },
      { number: 3, action: 'Analyze budget vs staffing capacity' },
      { number: 4, action: 'Create hiring plan and timeline' },
      { number: 5, action: 'Present plan to leadership' },
    ],
  },

  // ========================================
  // IT BLUEPRINTS
  // ========================================
  {
    id: 'it-access-provisioning',
    name: 'Access Provisioning',
    description: 'Grant and revoke system access',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Engineering'],
    defaultSteps: [
      { number: 1, action: 'Review access request and approvals' },
      { number: 2, action: 'Verify requestor identity and role' },
      { number: 3, action: 'Create user accounts and assign permissions' },
      { number: 4, action: 'Send credentials securely to user' },
      { number: 5, action: 'Document access grant in audit log' },
    ],
  },
  {
    id: 'it-change-management',
    name: 'Change Management',
    description: 'Process system change requests',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    typicalDepartments: ['Engineering'],
    defaultSteps: [
      { number: 1, action: 'Review and approve change requests' },
      { number: 2, action: 'Assess risk and impact of changes' },
      { number: 3, action: 'Schedule implementation window' },
      { number: 4, action: 'Coordinate with affected teams' },
      { number: 5, action: 'Document change and post-implementation review' },
    ],
  },
  {
    id: 'it-system-maintenance',
    name: 'System Maintenance',
    description: 'Perform regular system updates',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'monthly',
    typicalDepartments: ['Engineering'],
    defaultSteps: [
      { number: 1, action: 'Review pending system updates and patches' },
      { number: 2, action: 'Test updates in staging environment' },
      { number: 3, action: 'Schedule maintenance window' },
      { number: 4, action: 'Apply updates to production' },
      { number: 5, action: 'Verify systems are operational post-update' },
    ],
  },
  {
    id: 'it-security-monitoring',
    name: 'Security Monitoring',
    description: 'Monitor for security threats',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
    typicalDepartments: ['Engineering'],
    defaultSteps: [
      { number: 1, action: 'Review security alerts and logs' },
      { number: 2, action: 'Investigate suspicious activity' },
      { number: 3, action: 'Take remediation actions as needed' },
      { number: 4, action: 'Update security incident log' },
      { number: 5, action: 'Report critical issues to leadership' },
    ],
  },
  {
    id: 'it-disaster-recovery',
    name: 'Disaster Recovery',
    description: 'Test and maintain DR procedures',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '4 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Engineering'],
    defaultSteps: [
      { number: 1, action: 'Review disaster recovery plan' },
      { number: 2, action: 'Schedule DR test exercise' },
      { number: 3, action: 'Execute recovery procedures in test environment' },
      { number: 4, action: 'Document test results and gaps' },
      { number: 5, action: 'Update DR plan based on findings' },
    ],
  },
  {
    id: 'it-vendor-onboarding',
    name: 'Vendor Onboarding',
    description: 'Onboard new technology vendors',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Engineering'],
    defaultSteps: [
      { number: 1, action: 'Review vendor contract and SLA' },
      { number: 2, action: 'Complete security and compliance review' },
      { number: 3, action: 'Set up vendor access and integrations' },
      { number: 4, action: 'Document vendor details and contacts' },
      { number: 5, action: 'Schedule kickoff meeting' },
    ],
  },
  {
    id: 'it-license-management',
    name: 'License Management',
    description: 'Track and renew software licenses',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'monthly',
    typicalDepartments: ['Engineering'],
    defaultSteps: [
      { number: 1, action: 'Review license inventory and expiration dates' },
      { number: 2, action: 'Identify licenses needing renewal' },
      { number: 3, action: 'Verify user counts and license utilization' },
      { number: 4, action: 'Process renewals or adjustments' },
      { number: 5, action: 'Update license tracking system' },
    ],
  },

  // ========================================
  // ADDITIONAL SALES BLUEPRINTS
  // ========================================
  {
    id: 'sales-lead-qualification',
    name: 'Lead Qualification',
    description: 'Qualify incoming leads',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Sales'],
    defaultSteps: [
      { number: 1, action: 'Review new leads in CRM' },
      { number: 2, action: 'Research company and decision makers' },
      { number: 3, action: 'Score lead based on fit and intent' },
      { number: 4, action: 'Route qualified leads to appropriate rep' },
      { number: 5, action: 'Schedule initial outreach' },
    ],
  },
  {
    id: 'sales-proposal-creation',
    name: 'Proposal Creation',
    description: 'Create client proposals',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    typicalDepartments: ['Sales'],
    defaultSteps: [
      { number: 1, action: 'Gather client requirements and pain points' },
      { number: 2, action: 'Create customized solution proposal' },
      { number: 3, action: 'Develop pricing and package options' },
      { number: 4, action: 'Review proposal with sales manager' },
      { number: 5, action: 'Send proposal and schedule follow-up' },
    ],
  },
  {
    id: 'sales-contract-negotiation',
    name: 'Contract Negotiation',
    description: 'Negotiate and close deals',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Sales'],
    defaultSteps: [
      { number: 1, action: 'Review customer requirements and concerns' },
      { number: 2, action: 'Draft contract terms and pricing' },
      { number: 3, action: 'Negotiate terms with customer' },
      { number: 4, action: 'Get internal approvals for concessions' },
      { number: 5, action: 'Finalize and execute contract' },
    ],
  },
  {
    id: 'sales-client-renewals',
    name: 'Client Renewals',
    description: 'Manage contract renewals',
    category: 'operations',
    deliverableType: 'email',
    estimatedTime: '1 hour',
    frequency: 'monthly',
    typicalDepartments: ['Sales', 'Customer Success'],
    defaultSteps: [
      { number: 1, action: 'Identify contracts up for renewal' },
      { number: 2, action: 'Review account health and satisfaction' },
      { number: 3, action: 'Prepare renewal proposal with any upsells' },
      { number: 4, action: 'Schedule renewal discussion with client' },
      { number: 5, action: 'Process renewal and update CRM' },
    ],
  },
  {
    id: 'sales-quote-generation',
    name: 'Quote Generation',
    description: 'Create and send price quotes',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Sales'],
    defaultSteps: [
      { number: 1, action: 'Collect product/service requirements from customer' },
      { number: 2, action: 'Calculate pricing based on volume and terms' },
      { number: 3, action: 'Generate formal quote document' },
      { number: 4, action: 'Review and send to customer' },
    ],
  },
  {
    id: 'sales-territory-management',
    name: 'Territory Management',
    description: 'Manage sales territories and assignments',
    category: 'planning',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Sales'],
    defaultSteps: [
      { number: 1, action: 'Review current territory assignments' },
      { number: 2, action: 'Analyze territory performance and coverage' },
      { number: 3, action: 'Rebalance territories based on opportunity' },
      { number: 4, action: 'Communicate changes to sales team' },
      { number: 5, action: 'Update CRM with new assignments' },
    ],
  },
  {
    id: 'sales-commission-tracking',
    name: 'Commission Tracking',
    description: 'Calculate and track sales commissions',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Sales'],
    defaultSteps: [
      { number: 1, action: 'Pull closed deals and revenue data' },
      { number: 2, action: 'Calculate commissions per rep' },
      { number: 3, action: 'Review for accuracy and adjustments' },
      { number: 4, action: 'Submit to finance for payment' },
      { number: 5, action: 'Distribute commission statements to reps' },
    ],
  },

  // ========================================
  // CUSTOMER SERVICE BLUEPRINTS
  // ========================================
  {
    id: 'cs-complaint-handling',
    name: 'Complaint Handling',
    description: 'Resolve customer complaints',
    category: 'operations',
    deliverableType: 'email',
    estimatedTime: '1 hour',
    frequency: 'daily',
    typicalDepartments: ['Customer Success'],
    defaultSteps: [
      { number: 1, action: 'Review complaint details and customer history' },
      { number: 2, action: 'Investigate issue and root cause' },
      { number: 3, action: 'Provide resolution or compensation' },
      { number: 4, action: 'Follow up with customer to confirm satisfaction' },
      { number: 5, action: 'Document complaint and resolution' },
    ],
  },
  {
    id: 'cs-query-resolution',
    name: 'Query Resolution',
    description: 'Answer customer queries',
    category: 'operations',
    deliverableType: 'email',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Customer Success'],
    defaultSteps: [
      { number: 1, action: 'Review customer query' },
      { number: 2, action: 'Research answer in knowledge base' },
      { number: 3, action: 'Provide detailed response to customer' },
      { number: 4, action: 'Follow up if additional assistance needed' },
    ],
  },
  {
    id: 'cs-account-inquiries',
    name: 'Account Inquiries',
    description: 'Handle account-related questions',
    category: 'operations',
    deliverableType: 'email',
    estimatedTime: '30 minutes',
    frequency: 'daily',
    typicalDepartments: ['Customer Success'],
    defaultSteps: [
      { number: 1, action: 'Verify customer identity' },
      { number: 2, action: 'Look up account information' },
      { number: 3, action: 'Provide requested information or updates' },
      { number: 4, action: 'Update customer record with inquiry details' },
    ],
  },
  {
    id: 'cs-escalation-management',
    name: 'Escalation Management',
    description: 'Manage escalated issues',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '1.5 hours',
    frequency: 'weekly',
    typicalDepartments: ['Customer Success'],
    defaultSteps: [
      { number: 1, action: 'Review escalated cases and priority' },
      { number: 2, action: 'Coordinate with relevant teams for resolution' },
      { number: 3, action: 'Keep customer informed of progress' },
      { number: 4, action: 'Ensure timely resolution' },
      { number: 5, action: 'Conduct post-resolution review' },
    ],
  },
  {
    id: 'cs-feedback-collection',
    name: 'Feedback Collection',
    description: 'Gather customer feedback',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '1 hour',
    frequency: 'monthly',
    typicalDepartments: ['Customer Success'],
    defaultSteps: [
      { number: 1, action: 'Send feedback surveys to customers' },
      { number: 2, action: 'Collect and analyze responses' },
      { number: 3, action: 'Identify trends and improvement areas' },
      { number: 4, action: 'Share insights with product and leadership' },
    ],
  },
  {
    id: 'cs-sla-monitoring',
    name: 'SLA Monitoring',
    description: 'Track service level agreement compliance',
    category: 'reporting',
    deliverableType: 'report',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    typicalDepartments: ['Customer Success'],
    defaultSteps: [
      { number: 1, action: 'Pull SLA metrics (response time, resolution time)' },
      { number: 2, action: 'Identify SLA breaches' },
      { number: 3, action: 'Investigate root causes' },
      { number: 4, action: 'Create improvement action plan' },
      { number: 5, action: 'Report SLA performance to leadership' },
    ],
  },
  {
    id: 'cs-knowledge-base-updates',
    name: 'Knowledge Base Updates',
    description: 'Maintain customer support documentation',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Customer Success'],
    defaultSteps: [
      { number: 1, action: 'Review common customer questions' },
      { number: 2, action: 'Identify gaps in knowledge base' },
      { number: 3, action: 'Write or update articles' },
      { number: 4, action: 'Review with team for accuracy' },
      { number: 5, action: 'Publish and notify team of updates' },
    ],
  },
  {
    id: 'cs-channel-management',
    name: 'Channel Management',
    description: 'Manage multi-channel support queues',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '1 hour',
    frequency: 'daily',
    typicalDepartments: ['Customer Success'],
    defaultSteps: [
      { number: 1, action: 'Monitor all support channels (email, chat, phone)' },
      { number: 2, action: 'Route inquiries to appropriate team members' },
      { number: 3, action: 'Balance workload across channels' },
      { number: 4, action: 'Track channel-specific metrics' },
    ],
  },

  // ========================================
  // ADDITIONAL MARKETING BLUEPRINTS
  // ========================================
  {
    id: 'marketing-social-media',
    name: 'Social Media Management',
    description: 'Manage social media presence and engagement',
    category: 'communication',
    deliverableType: 'document',
    estimatedTime: '1 hour',
    frequency: 'daily',
    typicalDepartments: ['Marketing'],
    defaultSteps: [
      { number: 1, action: 'Review scheduled posts for the day' },
      { number: 2, action: 'Monitor mentions and engagement' },
      { number: 3, action: 'Respond to comments and messages' },
      { number: 4, action: 'Share relevant content and updates' },
      { number: 5, action: 'Track performance metrics' },
    ],
  },
  {
    id: 'marketing-brand-guidelines',
    name: 'Brand Guidelines',
    description: 'Maintain and enforce brand standards',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Marketing'],
    defaultSteps: [
      { number: 1, action: 'Review current brand guidelines' },
      { number: 2, action: 'Update with new brand elements or changes' },
      { number: 3, action: 'Ensure compliance across marketing materials' },
      { number: 4, action: 'Train team on guidelines' },
      { number: 5, action: 'Distribute updated guidelines' },
    ],
  },
  {
    id: 'marketing-event-management',
    name: 'Event Management',
    description: 'Plan and execute marketing events',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '5 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Marketing'],
    defaultSteps: [
      { number: 1, action: 'Define event goals and target audience' },
      { number: 2, action: 'Plan event logistics (venue, catering, materials)' },
      { number: 3, action: 'Create promotional campaign' },
      { number: 4, action: 'Execute event and track attendance' },
      { number: 5, action: 'Conduct post-event analysis and follow-up' },
    ],
  },
  {
    id: 'marketing-analytics',
    name: 'Marketing Analytics',
    description: 'Track and report on campaign performance',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Marketing'],
    defaultSteps: [
      { number: 1, action: 'Pull marketing metrics from all channels' },
      { number: 2, action: 'Analyze performance vs goals' },
      { number: 3, action: 'Identify top and bottom performers' },
      { number: 4, action: 'Create insights and recommendations' },
      { number: 5, action: 'Present findings to team and leadership' },
    ],
  },
  {
    id: 'marketing-lead-nurturing',
    name: 'Lead Nurturing',
    description: 'Nurture leads through email campaigns',
    category: 'communication',
    deliverableType: 'email',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    typicalDepartments: ['Marketing'],
    defaultSteps: [
      { number: 1, action: 'Segment leads by stage and interest' },
      { number: 2, action: 'Create targeted email campaigns' },
      { number: 3, action: 'Schedule and send campaigns' },
      { number: 4, action: 'Monitor open and click rates' },
      { number: 5, action: 'Adjust campaigns based on performance' },
    ],
  },
  {
    id: 'marketing-partner-marketing',
    name: 'Partner Marketing',
    description: 'Coordinate co-marketing with partners',
    category: 'coordination',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'monthly',
    typicalDepartments: ['Marketing'],
    defaultSteps: [
      { number: 1, action: 'Identify co-marketing opportunities with partners' },
      { number: 2, action: 'Develop joint marketing plan' },
      { number: 3, action: 'Create co-branded materials' },
      { number: 4, action: 'Execute campaign with partner' },
      { number: 5, action: 'Track and share results' },
    ],
  },
  {
    id: 'marketing-budget-tracking',
    name: 'Budget Tracking',
    description: 'Track marketing spend and ROI',
    category: 'reporting',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'monthly',
    typicalDepartments: ['Marketing'],
    defaultSteps: [
      { number: 1, action: 'Collect spend data from all campaigns' },
      { number: 2, action: 'Compare actual vs budgeted spend' },
      { number: 3, action: 'Calculate ROI for each campaign' },
      { number: 4, action: 'Identify optimization opportunities' },
      { number: 5, action: 'Report budget status to leadership' },
    ],
  },

  // ========================================
  // LEGAL BLUEPRINTS
  // ========================================
  {
    id: 'legal-contract-review',
    name: 'Contract Review',
    description: 'Review and approve legal contracts',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    defaultSteps: [
      { number: 1, action: 'Review contract terms and obligations' },
      { number: 2, action: 'Identify legal risks and red flags' },
      { number: 3, action: 'Propose edits and negotiate terms' },
      { number: 4, action: 'Get final approval from stakeholders' },
      { number: 5, action: 'File executed contract' },
    ],
  },
  {
    id: 'legal-regulatory-filings',
    name: 'Regulatory Filings',
    description: 'Prepare and submit regulatory documents',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    defaultSteps: [
      { number: 1, action: 'Review regulatory filing requirements' },
      { number: 2, action: 'Gather required documentation' },
      { number: 3, action: 'Prepare filing documents' },
      { number: 4, action: 'Review with compliance team' },
      { number: 5, action: 'Submit to regulatory authority' },
    ],
  },
  {
    id: 'legal-litigation-management',
    name: 'Litigation Management',
    description: 'Manage legal disputes and cases',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '4 hours',
    frequency: 'ad-hoc',
    defaultSteps: [
      { number: 1, action: 'Review case details and evidence' },
      { number: 2, action: 'Coordinate with external counsel' },
      { number: 3, action: 'Prepare legal strategy and filings' },
      { number: 4, action: 'Attend hearings and depositions' },
      { number: 5, action: 'Document case outcomes and learnings' },
    ],
  },
  {
    id: 'legal-policy-updates',
    name: 'Policy Updates',
    description: 'Update internal policies and procedures',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'quarterly',
    defaultSteps: [
      { number: 1, action: 'Review existing policies for updates needed' },
      { number: 2, action: 'Draft policy changes' },
      { number: 3, action: 'Review with stakeholders and get approval' },
      { number: 4, action: 'Communicate updated policies to organization' },
      { number: 5, action: 'Update policy repository' },
    ],
  },
  {
    id: 'legal-advisory',
    name: 'Legal Advisory',
    description: 'Provide legal guidance to business units',
    category: 'operations',
    deliverableType: 'email',
    estimatedTime: '1 hour',
    frequency: 'weekly',
    defaultSteps: [
      { number: 1, action: 'Review legal question or issue' },
      { number: 2, action: 'Research applicable laws and precedents' },
      { number: 3, action: 'Provide legal advice and recommendations' },
      { number: 4, action: 'Document guidance for future reference' },
    ],
  },
  {
    id: 'legal-ip-management',
    name: 'IP Management',
    description: 'Track patents and trademarks',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '1.5 hours',
    frequency: 'quarterly',
    defaultSteps: [
      { number: 1, action: 'Review IP portfolio and renewal dates' },
      { number: 2, action: 'Process new IP applications' },
      { number: 3, action: 'Monitor for potential IP infringement' },
      { number: 4, action: 'Coordinate with IP counsel on issues' },
      { number: 5, action: 'Update IP tracking system' },
    ],
  },
  {
    id: 'legal-nda-processing',
    name: 'NDA Processing',
    description: 'Process non-disclosure agreements',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'weekly',
    defaultSteps: [
      { number: 1, action: 'Review NDA request and counterparty' },
      { number: 2, action: 'Use standard template or negotiate terms' },
      { number: 3, action: 'Get approvals from stakeholders' },
      { number: 4, action: 'Execute NDA' },
      { number: 5, action: 'File and track NDA' },
    ],
  },
  {
    id: 'legal-research',
    name: 'Legal Research',
    description: 'Research legal precedents and regulations',
    category: 'analysis',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    defaultSteps: [
      { number: 1, action: 'Define research question and scope' },
      { number: 2, action: 'Research case law and regulations' },
      { number: 3, action: 'Analyze findings and implications' },
      { number: 4, action: 'Prepare research memo' },
      { number: 5, action: 'Present findings to stakeholders' },
    ],
  },

  // ========================================
  // COMPLIANCE BLUEPRINTS
  // ========================================
  {
    id: 'compliance-regulatory-monitoring',
    name: 'Regulatory Monitoring',
    description: 'Monitor regulatory changes and updates',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    defaultSteps: [
      { number: 1, action: 'Review regulatory news and updates' },
      { number: 2, action: 'Assess impact on organization' },
      { number: 3, action: 'Document changes and requirements' },
      { number: 4, action: 'Communicate to affected teams' },
      { number: 5, action: 'Update compliance procedures' },
    ],
  },
  {
    id: 'compliance-testing',
    name: 'Compliance Testing',
    description: 'Test adherence to regulatory requirements',
    category: 'review',
    deliverableType: 'report',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    defaultSteps: [
      { number: 1, action: 'Define testing scope and samples' },
      { number: 2, action: 'Execute compliance tests' },
      { number: 3, action: 'Document findings and exceptions' },
      { number: 4, action: 'Prepare remediation plan for issues' },
      { number: 5, action: 'Report results to management' },
    ],
  },
  {
    id: 'compliance-aml-screening',
    name: 'AML Screening',
    description: 'Screen transactions for money laundering',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
    defaultSteps: [
      { number: 1, action: 'Review flagged transactions' },
      { number: 2, action: 'Investigate customer and transaction patterns' },
      { number: 3, action: 'Document findings and risk assessment' },
      { number: 4, action: 'Escalate suspicious activity as needed' },
      { number: 5, action: 'Update AML case management system' },
    ],
  },
  {
    id: 'compliance-sanctions-checks',
    name: 'Sanctions Checks',
    description: 'Verify against sanctions lists',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '1 hour',
    frequency: 'daily',
    defaultSteps: [
      { number: 1, action: 'Screen customers and transactions against sanctions lists' },
      { number: 2, action: 'Investigate potential matches' },
      { number: 3, action: 'Document screening results' },
      { number: 4, action: 'Block or escalate sanctioned entities' },
      { number: 5, action: 'Update sanctions monitoring system' },
    ],
  },
  {
    id: 'compliance-reporting',
    name: 'Compliance Reporting',
    description: 'Generate compliance reports for regulators',
    category: 'reporting',
    deliverableType: 'report',
    estimatedTime: '3 hours',
    frequency: 'monthly',
    defaultSteps: [
      { number: 1, action: 'Gather compliance data and metrics' },
      { number: 2, action: 'Prepare regulatory reports' },
      { number: 3, action: 'Review with compliance officer' },
      { number: 4, action: 'Submit to regulators' },
      { number: 5, action: 'File reports and confirmations' },
    ],
  },
  {
    id: 'compliance-policy-enforcement',
    name: 'Policy Enforcement',
    description: 'Ensure policies are followed across teams',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    defaultSteps: [
      { number: 1, action: 'Review policy compliance metrics' },
      { number: 2, action: 'Identify violations and exceptions' },
      { number: 3, action: 'Investigate root causes' },
      { number: 4, action: 'Implement corrective actions' },
      { number: 5, action: 'Report on policy adherence' },
    ],
  },
  {
    id: 'compliance-training-tracking',
    name: 'Training Tracking',
    description: 'Track compliance training completion',
    category: 'operations',
    deliverableType: 'spreadsheet',
    estimatedTime: '1 hour',
    frequency: 'monthly',
    defaultSteps: [
      { number: 1, action: 'Review training completion rates' },
      { number: 2, action: 'Identify employees needing training' },
      { number: 3, action: 'Send reminders to complete training' },
      { number: 4, action: 'Track and document completion' },
      { number: 5, action: 'Report training status to management' },
    ],
  },
  {
    id: 'compliance-incident-reporting',
    name: 'Incident Reporting',
    description: 'Report compliance incidents',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    defaultSteps: [
      { number: 1, action: 'Document incident details' },
      { number: 2, action: 'Assess severity and regulatory implications' },
      { number: 3, action: 'Prepare incident report' },
      { number: 4, action: 'Submit to regulators if required' },
      { number: 5, action: 'Implement corrective measures' },
    ],
  },
  {
    id: 'compliance-vendor-due-diligence',
    name: 'Vendor Due Diligence',
    description: 'Assess third-party compliance',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    defaultSteps: [
      { number: 1, action: 'Review vendor compliance documentation' },
      { number: 2, action: 'Assess vendor risk profile' },
      { number: 3, action: 'Conduct site visits or audits if needed' },
      { number: 4, action: 'Document findings and risk rating' },
      { number: 5, action: 'Approve or require remediation' },
    ],
  },

  // ========================================
  // RISK BLUEPRINTS
  // ========================================
  {
    id: 'risk-assessment',
    name: 'Risk Assessment',
    description: 'Evaluate and document business risks',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    defaultSteps: [
      { number: 1, action: 'Identify potential risks across business' },
      { number: 2, action: 'Assess likelihood and impact of each risk' },
      { number: 3, action: 'Document risk register and ratings' },
      { number: 4, action: 'Propose risk mitigation strategies' },
      { number: 5, action: 'Present to risk committee' },
    ],
  },
  {
    id: 'risk-credit-analysis',
    name: 'Credit Analysis',
    description: 'Analyze creditworthiness of clients',
    category: 'analysis',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    defaultSteps: [
      { number: 1, action: 'Gather client financial statements' },
      { number: 2, action: 'Analyze financial ratios and trends' },
      { number: 3, action: 'Review credit bureau reports' },
      { number: 4, action: 'Assign credit rating and limits' },
      { number: 5, action: 'Document credit decision' },
    ],
  },
  {
    id: 'risk-fraud-detection',
    name: 'Fraud Detection',
    description: 'Identify and investigate fraud patterns',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'daily',
    defaultSteps: [
      { number: 1, action: 'Review fraud alerts and suspicious patterns' },
      { number: 2, action: 'Investigate flagged transactions' },
      { number: 3, action: 'Gather evidence and documentation' },
      { number: 4, action: 'Take preventive action (block accounts, etc.)' },
      { number: 5, action: 'Report to authorities if needed' },
    ],
  },
  {
    id: 'risk-reporting',
    name: 'Risk Reporting',
    description: 'Prepare risk reports for management',
    category: 'reporting',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    defaultSteps: [
      { number: 1, action: 'Collect risk metrics and data' },
      { number: 2, action: 'Analyze key risk indicators' },
      { number: 3, action: 'Prepare executive risk dashboard' },
      { number: 4, action: 'Highlight emerging risks and trends' },
      { number: 5, action: 'Present to leadership and board' },
    ],
  },
  {
    id: 'risk-stress-testing',
    name: 'Stress Testing',
    description: 'Conduct scenario-based stress tests',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '4 hours',
    frequency: 'quarterly',
    defaultSteps: [
      { number: 1, action: 'Define stress test scenarios' },
      { number: 2, action: 'Gather relevant data and assumptions' },
      { number: 3, action: 'Run stress test models' },
      { number: 4, action: 'Analyze results and impact' },
      { number: 5, action: 'Document findings and recommendations' },
    ],
  },
  {
    id: 'risk-incident-response',
    name: 'Incident Response',
    description: 'Respond to risk events and incidents',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'ad-hoc',
    defaultSteps: [
      { number: 1, action: 'Assess incident severity and impact' },
      { number: 2, action: 'Activate incident response team' },
      { number: 3, action: 'Contain and mitigate incident' },
      { number: 4, action: 'Communicate to stakeholders' },
      { number: 5, action: 'Conduct post-incident review' },
    ],
  },
  {
    id: 'risk-control-testing',
    name: 'Control Testing',
    description: 'Test effectiveness of risk controls',
    category: 'review',
    deliverableType: 'report',
    estimatedTime: '3 hours',
    frequency: 'quarterly',
    defaultSteps: [
      { number: 1, action: 'Identify controls to test' },
      { number: 2, action: 'Execute control tests' },
      { number: 3, action: 'Document control effectiveness' },
      { number: 4, action: 'Identify control gaps or weaknesses' },
      { number: 5, action: 'Recommend improvements' },
    ],
  },
  {
    id: 'risk-appetite-monitoring',
    name: 'Appetite Monitoring',
    description: 'Monitor against risk appetite limits',
    category: 'operations',
    deliverableType: 'report',
    estimatedTime: '1.5 hours',
    frequency: 'monthly',
    defaultSteps: [
      { number: 1, action: 'Review risk appetite framework' },
      { number: 2, action: 'Monitor risk metrics against limits' },
      { number: 3, action: 'Identify breaches or near-breaches' },
      { number: 4, action: 'Escalate issues to risk committee' },
      { number: 5, action: 'Document monitoring results' },
    ],
  },

  // ========================================
  // ADDITIONAL PRODUCT BLUEPRINTS
  // ========================================
  {
    id: 'product-requirements-gathering',
    name: 'Requirements Gathering',
    description: 'Collect and document product requirements',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Interview stakeholders and users' },
      { number: 2, action: 'Document functional and non-functional requirements' },
      { number: 3, action: 'Prioritize requirements' },
      { number: 4, action: 'Review with engineering and design' },
      { number: 5, action: 'Get sign-off from stakeholders' },
    ],
  },
  {
    id: 'product-user-research',
    name: 'User Research',
    description: 'Conduct user interviews and surveys',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '4 hours',
    frequency: 'monthly',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Define research questions and goals' },
      { number: 2, action: 'Recruit participants' },
      { number: 3, action: 'Conduct interviews or surveys' },
      { number: 4, action: 'Analyze findings and insights' },
      { number: 5, action: 'Share research report with team' },
    ],
  },
  {
    id: 'product-feature-testing',
    name: 'Feature Testing',
    description: 'Test new features before release',
    category: 'review',
    deliverableType: 'document',
    estimatedTime: '2 hours',
    frequency: 'weekly',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Review feature requirements and acceptance criteria' },
      { number: 2, action: 'Execute test cases and scenarios' },
      { number: 3, action: 'Document bugs and issues' },
      { number: 4, action: 'Verify fixes and retest' },
      { number: 5, action: 'Approve for release' },
    ],
  },
  {
    id: 'product-launch',
    name: 'Product Launch',
    description: 'Coordinate product launches and rollouts',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '5 hours',
    frequency: 'quarterly',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Create launch plan and timeline' },
      { number: 2, action: 'Coordinate with marketing on messaging' },
      { number: 3, action: 'Prepare internal training and documentation' },
      { number: 4, action: 'Execute launch and monitor rollout' },
      { number: 5, action: 'Gather feedback and metrics' },
    ],
  },
  {
    id: 'product-backlog-grooming',
    name: 'Backlog Grooming',
    description: 'Prioritize and refine product backlog',
    category: 'planning',
    deliverableType: 'document',
    estimatedTime: '1.5 hours',
    frequency: 'weekly',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Review backlog items' },
      { number: 2, action: 'Refine user stories and acceptance criteria' },
      { number: 3, action: 'Prioritize based on value and effort' },
      { number: 4, action: 'Remove outdated or irrelevant items' },
      { number: 5, action: 'Prepare top items for sprint planning' },
    ],
  },
  {
    id: 'product-competitor-analysis',
    name: 'Competitor Analysis',
    description: 'Track and analyze competitor products',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Research competitor product updates' },
      { number: 2, action: 'Compare features and positioning' },
      { number: 3, action: 'Analyze pricing and market strategy' },
      { number: 4, action: 'Identify gaps and opportunities' },
      { number: 5, action: 'Share insights with team' },
    ],
  },
  {
    id: 'product-beta-management',
    name: 'Beta Management',
    description: 'Manage beta testing programs',
    category: 'operations',
    deliverableType: 'document',
    estimatedTime: '3 hours',
    frequency: 'ad-hoc',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Recruit and onboard beta participants' },
      { number: 2, action: 'Distribute beta version and instructions' },
      { number: 3, action: 'Collect feedback and bug reports' },
      { number: 4, action: 'Analyze feedback and prioritize fixes' },
      { number: 5, action: 'Thank participants and share outcomes' },
    ],
  },
  {
    id: 'product-feedback-synthesis',
    name: 'Feedback Synthesis',
    description: 'Analyze and prioritize user feedback',
    category: 'analysis',
    deliverableType: 'report',
    estimatedTime: '2 hours',
    frequency: 'monthly',
    typicalDepartments: ['Product'],
    defaultSteps: [
      { number: 1, action: 'Collect feedback from all sources' },
      { number: 2, action: 'Categorize and tag feedback' },
      { number: 3, action: 'Identify common themes and requests' },
      { number: 4, action: 'Prioritize based on impact and frequency' },
      { number: 5, action: 'Update roadmap with feedback insights' },
    ],
  },

  // ========================================
  // GENERAL / CROSS-FUNCTIONAL BLUEPRINTS
  // ========================================
  {
    id: 'general-team-meeting',
    name: 'Team Meeting Prep',
    description: 'Prepare agenda and materials for team meeting',
    category: 'communication',
    deliverableType: 'document',
    estimatedTime: '30 minutes',
    frequency: 'weekly',
    defaultSteps: [
      { number: 1, action: 'Review action items from last meeting' },
      { number: 2, action: 'Gather updates from team members' },
      { number: 3, action: 'Create agenda with discussion topics' },
      { number: 4, action: 'Send agenda to team 24h in advance' },
    ],
  },
  {
    id: 'general-1on1-prep',
    name: '1-on-1 Meeting Prep',
    description: 'Prepare for 1-on-1 with direct report or manager',
    category: 'communication',
    deliverableType: 'document',
    estimatedTime: '15 minutes',
    frequency: 'weekly',
    defaultSteps: [
      { number: 1, action: 'Review previous 1-on-1 notes and action items' },
      { number: 2, action: 'Prepare topics to discuss (wins, blockers, feedback)' },
      { number: 3, action: 'Add items to shared doc' },
    ],
  },
  {
    id: 'general-project-status',
    name: 'Project Status Update',
    description: 'Send project status update to stakeholders',
    category: 'reporting',
    deliverableType: 'email',
    estimatedTime: '30 minutes',
    frequency: 'weekly',
    defaultSteps: [
      { number: 1, action: 'Review project milestones and progress' },
      { number: 2, action: 'Identify accomplishments, blockers, and risks' },
      { number: 3, action: 'Draft status email with RAG status' },
      { number: 4, action: 'Send to stakeholders and project team' },
    ],
  },
];

/**
 * Get blueprints relevant to a department
 */
export function getBlueprintsForDepartment(department: Department): WorkBlueprint[] {
  return BLUEPRINT_LIBRARY.filter(bp =>
    bp.typicalDepartments && bp.typicalDepartments.includes(department)
  );
}

/**
 * Get blueprints by category
 */
export function getBlueprintsByCategory(category: BlueprintCategory): WorkBlueprint[] {
  return BLUEPRINT_LIBRARY.filter(bp => bp.category === category);
}

/**
 * Get blueprint by ID
 */
export function getBlueprintById(id: string): WorkBlueprint | undefined {
  return BLUEPRINT_LIBRARY.find(bp => bp.id === id);
}

/**
 * Get all blueprints (for browsing)
 */
export function getAllBlueprints(): WorkBlueprint[] {
  return BLUEPRINT_LIBRARY;
}
