/**
 * Work Blueprint Types
 *
 * Blueprints are reusable work patterns that users can select during onboarding
 * or create themselves. Each blueprint defines a common work task with predefined steps.
 */

export type Department =
  | 'Product'
  | 'Engineering'
  | 'Finance'
  | 'Sales'
  | 'Marketing'
  | 'Operations'
  | 'Customer Success'
  | 'Data & Analytics'
  | 'Human Resources'
  | 'Legal'
  | 'Compliance'
  | 'Risk'
  | 'Executive'
  | 'Other';

/**
 * Identity Profile (extends existing identity profile in context_profiles)
 */
export interface IdentityProfileData {
  // Existing fields
  fullName: string;
  email: string;
  role?: string; // Legacy field
  responsibilities?: string[];
  authority?: string;

  // New fields for work blueprints
  department?: Department;
  jobRole?: string; // Free text job role
}

/**
 * Work Patterns Profile (new profile type in context_profiles)
 */
export interface WorkPatternsProfileData {
  // Blueprints user selected during onboarding
  selectedBlueprints: string[]; // Blueprint IDs

  // Custom blueprints user created
  customBlueprints: WorkBlueprint[];

  // Usage statistics
  blueprintUsage: Record<string, number>; // blueprint_id -> usage count
}

/**
 * Work Blueprint - A template for common work patterns
 * Note: Blueprints are templates only. Actual workflows with steps, inputs, and outputs
 * are generated by AI and saved to user_workflows table for reuse.
 */
export interface WorkBlueprint {
  id: string;
  name: string;
  description: string;
  category: BlueprintCategory;

  // Metadata
  deliverableType?: 'report' | 'presentation' | 'document' | 'email' | 'analysis' | 'spreadsheet';
  estimatedTime?: string; // e.g., "30 minutes", "2 hours"
  frequency?: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'ad-hoc';

  // Which departments typically use this blueprint
  typicalDepartments?: Department[];
}

export type BlueprintCategory =
  | 'reporting'       // Regular reports, status updates
  | 'planning'        // Planning activities, roadmaps
  | 'communication'   // Stakeholder updates, announcements
  | 'analysis'        // Data analysis, research
  | 'review'          // Reviews, approvals, assessments
  | 'coordination'    // Cross-team coordination
  | 'operations'      // Operational tasks
  | 'custom';         // User-created

/**
 * Grouped blueprints for display
 */
export interface BlueprintGroup {
  category: BlueprintCategory;
  displayName: string;
  blueprints: WorkBlueprint[];
}

/**
 * Onboarding state
 */
export interface OnboardingData {
  department: Department | null;
  jobRole: string; // Free text
}
