/**
 * Work Blueprint Types
 *
 * Blueprints are reusable work patterns that users can select during onboarding
 * or create themselves. Each blueprint defines a common work task with predefined steps.
 */

export type Department =
  | 'Product'
  | 'Engineering'
  | 'Finance'
  | 'Sales'
  | 'Marketing'
  | 'Operations'
  | 'Customer Success'
  | 'Data & Analytics'
  | 'Human Resources'
  | 'Legal'
  | 'Compliance'
  | 'Risk'
  | 'Executive'
  | 'Other';

/**
 * Identity Profile (extends existing identity profile in context_profiles)
 */
export interface IdentityProfileData {
  // Existing fields
  fullName: string;
  email: string;
  role?: string; // Legacy field
  responsibilities?: string[];
  authority?: string;

  // New fields for work blueprints
  department?: Department;
  jobRole?: string; // Free text job role
}

/**
 * A workflow record derived from a completed work_thread plan.
 * Stored in work_patterns profile to build context over time.
 */
export interface WorkflowRecord {
  threadId: string;
  name: string;            // thread title
  purpose: string;         // plan.deliverable_description
  deliverableType: string; // plan.deliverable_type
  skills: string[];        // deduplicated from plan.steps[].skill
  commonInputs: string[];  // from plan.inputs[].name
  updatedAt: string;       // ISO timestamp
}

/**
 * Work Patterns Profile (new profile type in context_profiles)
 */
export interface WorkPatternsProfileData {
  // Blueprints user selected during onboarding
  selectedBlueprints: string[]; // Blueprint IDs

  // Custom blueprints user created
  customBlueprints: WorkBlueprint[];

  // Usage statistics
  blueprintUsage: Record<string, number>; // blueprint_id -> usage count

  // Workflows created through chat (newest first, capped at 20)
  recentWorkflows: WorkflowRecord[];

  // Derived counts from recentWorkflows — for quick lookup
  deliverableTypes: Record<string, number>; // e.g. { presentation: 5, report: 2 }
  commonSkills: string[];                   // top skills by frequency
}

/**
 * Work Blueprint - A template for common work patterns
 * Note: Blueprints are templates only. Actual workflows with steps, inputs, and outputs
 * are generated by AI and saved to user_workflows table for reuse.
 */
export interface WorkBlueprint {
  id: string;
  name: string;
  description: string;
  category: BlueprintCategory;

  // Metadata
  deliverableType?: 'report' | 'presentation' | 'document' | 'email' | 'analysis' | 'spreadsheet';
  estimatedTime?: string; // e.g., "30 minutes", "2 hours"
  frequency?: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'ad-hoc';

  // Which departments typically use this blueprint
  typicalDepartments?: Department[];
}

export type BlueprintCategory =
  | 'reporting'       // Regular reports, status updates
  | 'planning'        // Planning activities, roadmaps
  | 'communication'   // Stakeholder updates, announcements
  | 'analysis'        // Data analysis, research
  | 'review'          // Reviews, approvals, assessments
  | 'coordination'    // Cross-team coordination
  | 'operations'      // Operational tasks
  | 'custom';         // User-created

/**
 * Grouped blueprints for display
 */
export interface BlueprintGroup {
  category: BlueprintCategory;
  displayName: string;
  blueprints: WorkBlueprint[];
}

/**
 * Saved Workflow — a reusable workflow shape saved from a completed thread.
 * Stored in the saved_workflows DB table.
 */
export interface SavedWorkflow {
  id: string;
  name: string;
  prompt: string;
  deliverable_types: string[];
  usage_count: number;
  last_used_at?: string;
  created_from_thread_id?: string;
  created_at: string;
}

/**
 * Onboarding state
 */
export interface OnboardingData {
  department: Department | null;
  jobRole: string; // Free text
}
